spring:
  cloud:
    stream:
      rabbit:
        bindings:
          input:
            consumer:
              auto-bind-dlq: true
              dlq-dead-letter-exchange:
              dlq-ttl: 10000
      bindings:
        input:
          destination: ex.stream.out2
          group: payment
          binder: rabbit1
          consumer:
            max-attempts: 1
        output:
          destination: ex.stream.out2
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: broker-host
                port: 30000
                username: guest
                password: guest
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:  
  port: ${PORT:2225}