# Docker-compose for Graylog

rabbit1:
  image: "rabbitmq:3-management"
  environment:
    RABBITMQ_DEFAULT_USER: "guest"
    RABBITMQ_DEFAULT_PASS: "guest"
  ports:
    - "30001:15672"
    - "30000:5672"
