spring:
  cloud:
    stream:
      bindings:
        input:
          destination: ex.stream.in
          binder: rabbit1
        output:
          destination: ex.stream.out
          group: order
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: broker-host
                port: 30000
                username: guest
                password: guest
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:  
  port: ${PORT:2222}